export interface Project {
  id: number;
  title: string;
  summary: string;
  images: string[];
  tags: string[];
  details: {
    details: string;
    // solution: string;
    // impact: string[];
  };
  externalLink?: {
    title: string;
    url: string;
  };
}
export const projects: Project[] = [
  {
    id: 1,
    title: "FID-Evaluator",
    summary: "A tool to analyze how the Fréchet inception distance (FID) behaves when reducing the dimensions of the embedding space using PCA.",
    images: [
      "https://github.com/Jonah-gr/FID-Evaluator/blob/main/public/Figure_1.png?raw=true",
      "https://github.com/Jonah-gr/FID-Evaluator/blob/main/public/deepfake_results.png?raw=true",
    ],
    tags: ["Python", "Machine Learning", "PyTorch", "Generative AI", "Research"],
    details: {
      details: "The FID is a metric for evaluating images generated by GAN networks or diffusion models. The goal is to make the calculation of the FID more sensitive to errors. We use a principal component analysis (PCA) to reduce the embedding space in order to better match the dimensional space (2048 dimensions) to the real images. To evaluate this, we noise the synthesized images and compare the percentage increase starting from the first FID value of the respective dimensional reduction of the embedding space. Reduction of the dimensions of the embedding space provided a more accurate representation of the quality of the generated images.",
      // solution: "Reduction of the dimensions of the embedding space using PCA.",
      // impact: ["Increased the sensitivity of the FID metric to errors.", "Provided a more accurate representation of the quality of the generated images."]
    }
  },
  {
    id: 2,
    title: "Reinforcement Learning in the Iterated Prisoner's Dilemma",
    summary: "Reinforcement Learning Agents are trained to optimize strategies against classical agents in the Iterated Prisoner's Dilemma.",
    images: [
      "https://github.com/Jonah-gr/Reinforcement-Learning-IPD/blob/main/poster/logos/tournament.png?raw=true",
    ],
    tags: ["Python", "Game Theory", "Reinforcement Learning", "Deep Learning"],
    details: {
      details: "The Iterated Prisoner's Dilemma (IPD) is a classic problem in game theory that models the tension between cooperation and competition in repeated interactions. In each round, two players independently decide either to cooperate or to defect. I wanted to explore and show that RL agents are capable of breaking through the dilemma and learning behaviors like generosity, forgiveness, and kindness that are the keys to long-term rewards.",
      // solution: "Developed a Python",
      // impact: [
      //   "Reduced reporting time from 5 days to a few hours, improving efficiency.",
      //   "Minimized errors in financial reports, ensuring data accuracy for decision-making."
      // ]
    }
  },
  {
    id: 3,
    title: "Image Recommender",
    summary: "A tool to recommend similar images to a given image based on its features, it's color histogram or it's YOLO bounding boxes.",
    images: [
      "/image_recommender1.jpg",
      "/image_recommender2.png",
      "/image_recommender3.png",
    ],
    tags: ["Python", "Machine Learning", "Image Processing", "Deep Learning"],
    details: {
      details: "",
      // solution: "Developed a Python",
      // impact: [
      //   "Reduced reporting time from 5 days to a few hours, improving efficiency.",
      //   "Minimized errors in financial reports, ensuring data accuracy for decision-making."
      // ]
    }
  }
];
