export interface Project {
  id: number;
  title: string;
  summary: string;
  images: string[];
  tags: string[];
  details: {
    details: string;
    // solution: string;
    // impact: string[];
  };
  externalLink?: {
    title: string;
    url: string;
  };
}
export const projects: Project[] = [
  {
    id: 1,
    title: "FID-Evaluator",
    summary: "A tool to analyze how the Fréchet inception distance (FID) behaves when reducing the dimensions of the embedding space using PCA.",
    images: [
      "https://github.com/Jonah-gr/FID-Evaluator/blob/main/public/Figure_1.png?raw=true",
      "https://github.com/Jonah-gr/FID-Evaluator/blob/main/public/deepfake_results.png?raw=true",
    ],
    tags: ["Python", "Machine Learning", "PyTorch", "Generative AI", "Research"],
    details: {
      details: "The FID is a metric for evaluating images generated by GAN networks or diffusion models. The goal is to make the calculation of the FID more sensitive to errors. We use a principal component analysis (PCA) to reduce the embedding space in order to better match the dimensional space (2048 dimensions) to the real images. To evaluate this, we noise the synthesized images and compare the percentage increase starting from the first FID value of the respective dimensional reduction of the embedding space. Reduction of the dimensions of the embedding space provided a more accurate representation of the quality of the generated images.",
      // solution: "Reduction of the dimensions of the embedding space using PCA.",
      // impact: ["Increased the sensitivity of the FID metric to errors.", "Provided a more accurate representation of the quality of the generated images."]
    },
    externalLink: {
      title: "FID-Evaluator on Github",
      url: "https://github.com/Jonah-gr/FID-Evaluator",
    }
  },
  {
    id: 2,
    title: "Reinforcement Learning in the Iterated Prisoner's Dilemma",
    summary: "Reinforcement Learning Agents are trained to optimize strategies against classical agents in the Iterated Prisoner's Dilemma.",
    images: [
      "https://github.com/Jonah-gr/Reinforcement-Learning-IPD/blob/main/poster/logos/tournament.png?raw=true",
    ],
    tags: ["Python", "Game Theory", "Reinforcement Learning", "Deep Learning"],
    details: {
      details: "The Iterated Prisoner's Dilemma (IPD) is a classic problem in game theory that models the tension between cooperation and competition in repeated interactions. In each round, two players independently decide either to cooperate or to defect. I wanted to explore and show that RL agents are capable of breaking through the dilemma and learning behaviors like generosity, forgiveness, and kindness that are the keys to long-term rewards.",
    },
    externalLink: {
      title: "Reinforcement-Learning-IPD on Github",
      url: "https://github.com/Jonah-gr/Reinforcement-Learning-IPD",
    }
  },
  {
    id: 3,
    title: "Image Recommender",
    summary: "A tool to recommend similar images to a given image based on its features, it's color histogram or it's YOLO bounding boxes.",
    images: [
      "/image_recommender1.jpg",
      "/image_recommender2.png",
      "/image_recommender3.png",
    ],
    tags: ["Python", "Machine Learning", "Image Processing", "Deep Learning"],
    details: {
      details: "The program was tested with approx. 500000 images and achieved very good results. Thanks to clustering, the search is very fast and yet very precise. The logits of the Inception V3 model were used for the embedding-based search.",
    },
    externalLink: {
      title: "Image-recommender on Github",
      url: "https://github.com/AlhaririAnas/Image-recommender",
    }
  },
  {
    id: 4,
    title: "SFM-Image-Matcher",
    summary: "A tool to select the images whose camera poses are closest to given 3d points. This works through prior reconstruction using Structure from Motion (SfM).",
    images: [
      "/sfm_poses.png",
      "/sfm_flowers.gif"
    ],
    tags: ["Python", "Photogrammetry", "Image Processing"],
    details: {
      details: "The Structure from Motion (SfM) Image Matcher is a tool designed to streamline the process of selecting images that are the closest match to specified 3D points. By leveraging SfM algorithms, the script can analyze a collection of images and their corresponding camera positions to determine the proximity of each image to the provided 3D points.",
    },
    externalLink: {
      title: "SfM-Image-Matcher on Github",
      url: "https://github.com/Jonah-gr/SfM-Image-Matcher",
    }
  },
  {
    id: 5,
    title: "Requiem of Dread",
    summary: "A free-to-play roguelike game that we developed and marketed as a group of 4 students in few months. Developed using the Godot Engine and published on Steam.",
    images: [
      "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3447360/header.jpg?t=1739992637",
      "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3447360/ss_2454c634195473a11ff4af5cae3441b8981c14d9.600x338.jpg?t=1739992637",
      "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3447360/ss_e2b7e599833170bb228e90f40c3ed58768123459.600x338.jpg?t=1739992637"
    ],
    tags: ["Python", "Godot", "Game Development"],
    details: {
      details: "The minimalist gameplay and retro pixel graphics make it easy to get started and let you dive deep into the dark worlds of Requiem of Dread. Embark on an adventure in the darkness and defeat enemies and bosses of increasing difficulty. Fight your way through 3 hand-crafted dungeon maps, from haunted graveyards to monster-filled forests to the empty tombs in the pyramids. Beware of what you'll find there! We have composed a melodic horror soundtrack to accompany you through the thrilling experience. This is a student project created in Godot 4.3. In a group of four students, we had two months to learn and customize different techniques and create this alpha version. The music is handcrafted and composed to immerse the player in a world of death, destruction and unease. The bosses will do anything to keep you on your toes, so don't take too much time to enjoy their animations. The skill tree allows you to spend your collected coins on buffs. Open the skill tree, go on a shopping spree and come back to finally kill the Grim Reaper!",
    },
    externalLink: {
      title: "Requiem of Dread on Steam",
      url: "https://store.steampowered.com/app/3447360/Requiem_of_Dread/",
    }
  },
  {
    id: 6,
    title: "Ant Search Algorithm",
    summary: "A kivy application that tries to mimic the foraging behavior of ants for food.",
    images: [
      "/ant_search_example.png",
      // "https://github.com/heyitsalina/ant_search_algorithm/blob/main/images/basic_features.gif?raw=true",
      // "https://github.com/heyitsalina/ant_search_algorithm/blob/main/images/advanced_features.gif?raw=true",
    ],
    tags: ["Python", "Kivy"],
    details: {
      details: "This ant food search simulation offers an intuitive GUI to interact with the simulation. It allows oyu to directly influence the simulation environment and observe the complex behaviors of ants in their quest for food.",
    },
    externalLink: {
      title: "ant-search-algorithm on Github",
      url: "https://github.com/heyitsalina/ant_search_algorithm",
    }
  },
  {
    id: 7,
    title: "Chess Fraud Analysis",
    summary: "An analysis of chess games with regard to the fraud allegations against Hans Moke Niemann in 2022 and visualization in MS Power BI.",
    images: [
      "/niemann1.png",
      "/niemann2.png",
      "/niemann3.png",
    ],
    tags: ["MS Power BI"],
    details: {
      details: "The project involved data collection through web scraping and the evaluation of each move by Stockfish 11 to calculate the AI match. The aim was to look for anomalies in Niemann's game statistics. To do this, his statistics were compared with those of Magnus Carlsen and the comparable player Vincent Keymer. In the end, it emerged that Niemann's playing strength was not exceptional, but his ELO nevertheless increased the most.",
    }
  }
];
