export interface Project {
  id: number;
  title: string;
  summary: string;
  images: string[];
  tags: string[];
  details: {
    details: string;
    // solution: string;
    // impact: string[];
  };
  externalLink?: {
    title: string;
    url: string;
  };
}
export const projects: Project[] = [
  {
    id: 1,
    title: "FID-Evaluator",
    summary: "A tool to analyze how the Fréchet inception distance (FID) behaves when reducing the dimensions of the embedding space using PCA.",
    images: [
      "https://github.com/Jonah-gr/FID-Evaluator/blob/main/public/Figure_1.png?raw=true",
      "https://github.com/Jonah-gr/FID-Evaluator/blob/main/public/deepfake_results.png?raw=true",
    ],
    tags: ["Python", "Machine Learning", "PyTorch", "Generative AI", "Research"],
    details: {
      details: "The FID is a metric for evaluating images generated by GAN networks or diffusion models. The goal is to make the calculation of the FID more sensitive to errors. We use a principal component analysis (PCA) to reduce the embedding space in order to better match the dimensional space (2048 dimensions) to the real images. To evaluate this, we noise the synthesized images and compare the percentage increase starting from the first FID value of the respective dimensional reduction of the embedding space. Reduction of the dimensions of the embedding space provided a more accurate representation of the quality of the generated images.",
      // solution: "Reduction of the dimensions of the embedding space using PCA.",
      // impact: ["Increased the sensitivity of the FID metric to errors.", "Provided a more accurate representation of the quality of the generated images."]
    }
  },
  {
    id: 2,
    title: "Reinforcement Learning in the Iterated Prisoner's Dilemma",
    summary: "Reinforcement Learning Agents are trained to optimize strategies against classical agents in the Iterated Prisoner's Dilemma.",
    images: [
      "https://github.com/Jonah-gr/Reinforcement-Learning-IPD/blob/main/poster/logos/tournament.png?raw=true",
    ],
    tags: ["Python", "Game Theory", "Reinforcement Learning", "Deep Learning"],
    details: {
      details: "The Iterated Prisoner's Dilemma (IPD) is a classic problem in game theory that models the tension between cooperation and competition in repeated interactions. In each round, two players independently decide either to cooperate or to defect. I wanted to explore and show that RL agents are capable of breaking through the dilemma and learning behaviors like generosity, forgiveness, and kindness that are the keys to long-term rewards.",
    }
  },
  {
    id: 3,
    title: "Image Recommender",
    summary: "A tool to recommend similar images to a given image based on its features, it's color histogram or it's YOLO bounding boxes.",
    images: [
      "/image_recommender1.jpg",
      "/image_recommender2.png",
      "/image_recommender3.png",
    ],
    tags: ["Python", "Machine Learning", "Image Processing", "Deep Learning"],
    details: {
      details: "",
    }
  },
  {
    id: 4,
    title: "SFM-Image-Matcher",
    summary: "A tool to select the images whose camera poses are closest to given 3d points. This works through prior reconstruction using Structure from Motion (SfM).",
    images: [
      "/sfm_poses.png",
      "/sfm_flowers.gif"
    ],
    tags: ["Python", "Photogrammetry", "Image Processing"],
    details: {
      details: "",
    }
  },
  {
    id: 5,
    title: "Ant Search Algorithm",
    summary: "A kivy application that tries to mimic the foraging behavior of ants for food.",
    images: [
      "/ant_search_example.png",
      "https://github.com/heyitsalina/ant_search_algorithm/blob/main/images/basic_features.gif?raw=true",
      "https://github.com/heyitsalina/ant_search_algorithm/blob/main/images/advanced_features.gif?raw=true",
    ],
    tags: ["Python", "Machine Learning", "Image Processing", "Deep Learning"],
    details: {
      details: "",
    }
  },
  {
    id: 6,
    title: "Image Recommender",
    summary: "An analysis of chess games with regard to the fraud allegations against Hans Moke Niemann in 2022 and visualization in MS Power BI. The project involved data collection through web scraping and the evaluation of each move by Stockfish 11 to calculate the AI match.",
    images: [
      "/niemann1.png",
      "/niemann2.png",
      "/niemann3.png",
    ],
    tags: ["MS Power BI"],
    details: {
      details: "",
    }
  }
];
